// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package gateway

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SendDataRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendDataRequest) Reset()         { *m = SendDataRequest{} }
func (m *SendDataRequest) String() string { return proto.CompactTextString(m) }
func (*SendDataRequest) ProtoMessage()    {}
func (*SendDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_7265179725d15605, []int{0}
}
func (m *SendDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendDataRequest.Unmarshal(m, b)
}
func (m *SendDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendDataRequest.Marshal(b, m, deterministic)
}
func (dst *SendDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendDataRequest.Merge(dst, src)
}
func (m *SendDataRequest) XXX_Size() int {
	return xxx_messageInfo_SendDataRequest.Size(m)
}
func (m *SendDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendDataRequest proto.InternalMessageInfo

func (m *SendDataRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SendDataRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SendDataResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendDataResponse) Reset()         { *m = SendDataResponse{} }
func (m *SendDataResponse) String() string { return proto.CompactTextString(m) }
func (*SendDataResponse) ProtoMessage()    {}
func (*SendDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_7265179725d15605, []int{1}
}
func (m *SendDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendDataResponse.Unmarshal(m, b)
}
func (m *SendDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendDataResponse.Marshal(b, m, deterministic)
}
func (dst *SendDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendDataResponse.Merge(dst, src)
}
func (m *SendDataResponse) XXX_Size() int {
	return xxx_messageInfo_SendDataResponse.Size(m)
}
func (m *SendDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendDataResponse proto.InternalMessageInfo

func (m *SendDataResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*SendDataRequest)(nil), "gateway.SendDataRequest")
	proto.RegisterType((*SendDataResponse)(nil), "gateway.SendDataResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayClient interface {
	ReceiveSendData(ctx context.Context, in *SendDataRequest, opts ...grpc.CallOption) (*SendDataResponse, error)
}

type gatewayClient struct {
	cc *grpc.ClientConn
}

func NewGatewayClient(cc *grpc.ClientConn) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) ReceiveSendData(ctx context.Context, in *SendDataRequest, opts ...grpc.CallOption) (*SendDataResponse, error) {
	out := new(SendDataResponse)
	err := c.cc.Invoke(ctx, "/gateway.Gateway/ReceiveSendData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServer is the server API for Gateway service.
type GatewayServer interface {
	ReceiveSendData(context.Context, *SendDataRequest) (*SendDataResponse, error)
}

func RegisterGatewayServer(s *grpc.Server, srv GatewayServer) {
	s.RegisterService(&_Gateway_serviceDesc, srv)
}

func _Gateway_ReceiveSendData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).ReceiveSendData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.Gateway/ReceiveSendData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).ReceiveSendData(ctx, req.(*SendDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveSendData",
			Handler:    _Gateway_ReceiveSendData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_gateway_7265179725d15605) }

var fileDescriptor_gateway_7265179725d15605 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x8d, 0x68, 0x8b, 0x83, 0x52, 0x09, 0x22, 0x55, 0x2f, 0xa5, 0xa7, 0xe2, 0x21, 0x88,
	0x1e, 0xbd, 0x15, 0xa1, 0x1e, 0x4b, 0xfa, 0x09, 0xc6, 0x76, 0x28, 0x45, 0x6d, 0x62, 0x33, 0x71,
	0x77, 0xbf, 0xfd, 0xd2, 0x7f, 0x2c, 0x2c, 0x7b, 0x7b, 0x3f, 0x86, 0x1f, 0xf3, 0x1e, 0xdc, 0xb4,
	0xc8, 0xb4, 0xc1, 0x9d, 0xb2, 0x83, 0x61, 0x23, 0xc3, 0x05, 0xd3, 0x77, 0x88, 0x2a, 0xea, 0x9b,
	0x0f, 0x64, 0xd4, 0xf4, 0xe7, 0xc9, 0xb1, 0xbc, 0x83, 0x4b, 0x36, 0xdf, 0xd4, 0xc7, 0x22, 0x11,
	0xd9, 0x95, 0x9e, 0x41, 0x4a, 0xb8, 0x68, 0x90, 0x31, 0x3e, 0x4f, 0x44, 0x76, 0xad, 0xa7, 0x9c,
	0x3e, 0xc3, 0xed, 0x41, 0x76, 0xd6, 0xf4, 0x8e, 0xe4, 0x3d, 0x04, 0x8e, 0x91, 0xbd, 0x5b, 0xf4,
	0x85, 0x5e, 0x2b, 0x08, 0x8b, 0xf9, 0xa7, 0xfc, 0x84, 0x48, 0x53, 0x4d, 0xdd, 0x3f, 0xad, 0xb6,
	0x8c, 0xd5, 0xda, 0xef, 0xa8, 0xcd, 0xe3, 0xc3, 0x89, 0xcb, 0xfc, 0x2a, 0x3d, 0xcb, 0x5f, 0xe0,
	0xa9, 0x33, 0xaa, 0x1d, 0x6c, 0xad, 0x68, 0x8b, 0xbf, 0xf6, 0x87, 0x9c, 0x1a, 0x8c, 0x67, 0x6a,
	0x7d, 0xd7, 0x50, 0x1e, 0xe9, 0x31, 0x17, 0x63, 0x2e, 0xc7, 0xd9, 0xa5, 0xf8, 0x0a, 0xa6, 0xfd,
	0x6f, 0xfb, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0x0f, 0xf9, 0x81, 0x10, 0x01, 0x00, 0x00,
}
