http:
  domain: "0.0.0.0"
  port: 10004
db:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: ""
  name: "msg"
redis:
  addr: "127.0.0.1:6379"
  password: ""
  pool_size: 10
secret:
  jwt_key: "msg"
  pass_hash_salt: "msg"
rpc:
  host: "127.0.0.1"
  port: "10010"